FROM alpine:3.13

RUN apk update
RUN apk add strace gradle bash vim openjdk11-jdk

ENV SPRING_PROFILES_ACTIVE=docker

WORKDIR /application_source

ENTRYPOINT ["gradle", "--gradle-user-home=/tmp", "build", "-x", "test"]
